### ISSUE TITLE
!confess command

### ISSUE THREAD

**Issue by fdardenne** [fdardenne/DiscordSINFBot#1]
An anonymous confession system. 
Members send a DM to the bot with /confess <message>
The admin approve it or not in a private channel (with a react) to make the anonymous confession public or not

**Comment by NovAti0n** [comment]
I'll take care of that

**Comment by NovAti0n** [comment]
I think that this issue can be closed (PR #41)

**Comment by FelixGaudin** [comment]
Remove the person who approuve the confession
