### ISSUE TITLE
!pin command

### ISSUE THREAD

**Issue by fdardenne** [fdardenne/DiscordSINFBot#3]
In Discord, the pin feature is reserved for roles that have permission to manage messages (i.e. delete and pin).

We want a !pin command in response to a message to pin it.
Several cases are possible:
- If the person has a specific role, then the message is automatically pinned
- If the person has the permission to manage messages, then the message is automatically pinned
- Otherwise the bot submits the pin to a vote. If the vote is successful, the message is pinned

**Comment by obiwac** [comment]
Under which circumstances will a vote be considered successful? Perhaps after a certain amount of time has elapsed or once the total number of votes passes a certain threshold?

**Comment by fdardenne** [comment]
The old bot implemented a rather naive treshold. It would pin the message if the number of positive votes reached 5 and the number of negative votes did not exceed 5.

A better solution would be maybe to make a timer of 10 minutes like you propose. We could then pin the post after this time if enough people voted and the majority voted for pinning. What do you think about it?

**Comment by obiwac** [comment]
Seems good, I'll get to implementing it in a little bit. So lets say the conditions under which a message is pinned are if all of the following are true:
- 10 minutes have elapsed
- At least 5 people have voted in favor of pinning
- More people have voted in favor than against

**Comment by obiwac** [comment]
This issue can now be closed after #38
